find_curriculum:
  description: >
    Find all of the required classes for the program of {major} at {school} that are not in {previous_classes}
  expected_output: >
    A list of all the required classes for the program of {major} at {school} that are not in {previous_classes}
  agent: curriculum_finder

find_professor:
  description: >
    Find the best Professor who have the most positive reviews and highest scores on ratemyprof.com at {school}
  expected_output: >
    A list of the best Professors who have the most positive reviews and highest scores on ratemyprof.com at {school}
  agent: professor_finder

organize_calendar:
  description: >
    Organize the classes in a way that makes sense for the {major} program at {school}
  expected_output: >
    A calendar with all the classes organized in a way that makes sense for the {major} program at {school}
  agent: calendar_organizer